# renv activation stub — run `renv::restore()` to recreate the library.
# Generated by renv 1.0.x
local({
  if (requireNamespace("renv", quietly = TRUE)) {
    renv::load()
  } else {
    message(
      "renv is not installed. Run install.packages('renv') then renv::restore() ",
      "to recreate the project library."
    )
  }
})
